commerce_payment.commerce_payment_gateway.plugin.iveri_lite_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    test_key:
      type: string
      label: 'API Test Key'
    live_key:
      type: string
      label: 'API Live Key'
    submission_endpoint:
      type: string
      label: 'API Submission Endpoint'
    auth_info_endpoint:
      type: string
      label: 'API Authorization Endpoint'
    redirect_validation_hash:
      type: string
      label: 'Redirect validation key'
    transaction_mode:
      type: string
      label: 'Transaction mode'